"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Atom } from "lucide-react";

const QUESTIONS = [
 {q:"Which statement correctly describes Newton's First Law of Motion?",options:["A body always needs a force to keep moving","A body remains at rest or moves with uniform velocity in a straight line unless acted upon by an external unbalanced force","Every action has an equal and opposite reaction","Force is always equal to velocity"],answer:1,explain:"The PPT defines the First Law as the Law of Inertia."},
 {q:"According to Newton's Second Law, the rate of change of momentum is directly proportional to the:",options:["Mass only","Velocity only","Applied external force","Time only"],answer:2,explain:"The PPT states that the rate of change of momentum is directly proportional to the applied external force and occurs in its direction."},
 {q:"Which statement is Newton's Third Law of Motion?",options:["A body remains at rest unless pushed","Force equals mass divided by acceleration","For every action, there is an equal and opposite reaction","Velocity is always constant"],answer:2,explain:"The PPT states: For every action, there is an equal and opposite reaction."},
 {q:"Which equation is a correct formula for motion with constant acceleration?",options:["v = u + at","v = u − at²","s = ut + at","v = u² + 2as"],answer:0,explain:"The PPT lists v = u + at among the formulas of motion."},
 {q:"Which formula gives displacement using initial velocity, final velocity and time?",options:["s = (u − v)t","s = ½(u + v)t","s = (u + v)/t","s = uv + t"],answer:1,explain:"The PPT lists s = ½(u + v)t."},
 {q:"A car starts with an initial velocity of 5 m/s and accelerates at 2 m/s² for 4 s. What is its final velocity?",options:["9 m/s","11 m/s","13 m/s","15 m/s"],answer:2,explain:"v = u + at = 5 + (2×4) = 13 m/s."},
 {q:"An object starts from rest and accelerates at 3 m/s² for 5 s. What is its final velocity?",options:["8 m/s","12 m/s","15 m/s","18 m/s"],answer:2,explain:"u = 0, so v = 0 + (3×5) = 15 m/s."},
 {q:"A body has u = 10 m/s, a = 2 m/s² and t = 5 s. How far does it travel?",options:["50 m","60 m","70 m","75 m"],answer:3,explain:"s = ut + ½at² = 10×5 + ½×2×25 = 75 m."},
 {q:"A body changes velocity from 20 m/s to 30 m/s in 5 s. What distance does it travel during this uniformly accelerated motion?",options:["100 m","125 m","150 m","250 m"],answer:1,explain:"s = ½(u+v)t = ½(20+30)×5 = 125 m."},
 {q:"A body changes velocity from 5 m/s to 15 m/s while travelling 50 m. What is its acceleration?",options:["1 m/s²","2 m/s²","3 m/s²","4 m/s²"],answer:1,explain:"v² = u² + 2as → 225 = 25 + 100a, so a = 2 m/s²."},
 {q:"A 5 kg object accelerates at 2 m/s². What is the net force acting on it?",options:["2.5 N","7 N","10 N","20 N"],answer:2,explain:"Using F = ma, F = 5×2 = 10 N."},
 {q:"A force of 30 N acts on a 10 kg object. What acceleration does it produce?",options:["0.3 m/s²","3 m/s²","20 m/s²","300 m/s²"],answer:1,explain:"a = F/m = 30/10 = 3 m/s²."},
 {q:"In the tug-of-war example from the class, if F1 is the force on Team A by Team B and F2 is the force on Team B by Team A, which is correct?",options:["F1 = F2","F1 > F2 because Team A wins","F1 < F2 because Team A wins","None of the above"],answer:0,explain:"The PPT's example illustrates Newton's Third Law: the action and reaction forces are equal and opposite."},
 {q:"For a projectile launched with u = 20 m/s at θ = 90°, take g = 10 m/s². What is its maximum height?",options:["10 m","15 m","20 m","40 m"],answer:2,explain:"Hmax = u²sin²θ/(2g) = 400/(20) = 20 m."},
 {q:"A projectile is launched at 20 m/s at θ = 30°. Taking g = 10 m/s², what is its time of flight?",options:["1 s","2 s","3 s","4 s"],answer:1,explain:"T = 2u sinθ/g = 2×20×0.5/10 = 2 s."},
 {q:"A projectile is launched at 20 m/s at 45°. Taking g = 10 m/s², what is its horizontal range?",options:["20 m","30 m","40 m","80 m"],answer:2,explain:"R = u²sin2θ/g = 400×sin90°/10 = 40 m."},
 {q:"A projectile is launched vertically upward with u = 10 m/s. Taking g = 10 m/s², what is its maximum height?",options:["2.5 m","5 m","10 m","20 m"],answer:1,explain:"Hmax = u²sin²90°/(2g) = 100/20 = 5 m."},
 {q:"An object moves with an initial velocity of 15 m/s and zero acceleration. What is its velocity after 10 s?",options:["0 m/s","1.5 m/s","15 m/s","150 m/s"],answer:2,explain:"With a = 0, v = u + at = 15 m/s."},
 {q:"An object starts from rest and accelerates at 4 m/s² for 3 s. What displacement does it cover?",options:["6 m","12 m","18 m","36 m"],answer:2,explain:"s = ut + ½at² = 0 + ½×4×9 = 18 m."},
 {q:"An object has u = 10 m/s, a = 2 m/s² and s = 24 m. What is its final velocity?",options:["12 m/s","14 m/s","16 m/s","18 m/s"],answer:1,explain:"v² = u² + 2as = 100 + 96 = 196, so v = 14 m/s."},
];

export default function PhysicsHomework1(){
 const router=useRouter(); const params=useParams(); const [stage,setStage]=useState<"intro"|"quiz">("intro"); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [answers,setAnswers]=useState<number[]>(Array(20).fill(-1)); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const key="physics-1";
 useEffect(()=>{if(params?.assignment&&params.assignment!=="1")router.replace("/csca/homework/physics/1");},[params,router]);
 async function start(){setError("");if(!name.trim()||!phone.trim()){setError("Please enter your name and phone number.");return;}setLoading(true);try{const r=await fetch("/api/csca/homework?assignment="+key+"&phone="+encodeURIComponent(phone.trim()));const d=await r.json();if(d.submitted)router.push("/csca/homework/result/"+d.token);else setStage("quiz");}catch{setError("Could not check your previous submission. Please try again.");}finally{setLoading(false);}}
 async function submit(){setError("");if(answers.some(a=>a<0)){setError("Please answer all 20 questions before submitting.");return;}setLoading(true);const score=answers.reduce((n,a,i)=>n+(a===QUESTIONS[i].answer?1:0),0);try{const r=await fetch("/api/csca/homework",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignment:key,name:name.trim(),phone:phone.trim(),answers,score})});const d=await r.json();if(!r.ok){setError(d.error||"Submission failed.");return;}router.push("/csca/homework/result/"+d.token);}catch{setError("Submission failed. Please check your connection and try again.");}finally{setLoading(false);}}
 return <main className="min-h-screen bg-slate-50 text-[#0A1628]"><section className="bg-[#0A1628] text-white"><div className="mx-auto max-w-5xl px-5 py-8 md:px-8"><div className="flex items-center justify-between gap-3 text-sm font-bold text-slate-300"><Link href="/csca/homework" className="inline-flex items-center gap-2 hover:text-white"><ArrowLeft className="h-4 w-4"/> Homework</Link><span className="font-black"><span className="text-[#C8102E]">GL</span> Education · <span className="text-[#FFD700]">Study in China</span></span></div><div className="mt-9"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-[#FFD700]"><Atom className="h-4 w-4"/> Physics · Assignment 1</span><h1 className="mt-4 text-3xl font-black md:text-5xl">Motion & Kinematics — Class 1 Homework</h1><p className="mt-3 max-w-2xl text-slate-300">20 MCQs · 20 marks · 5 concepts & formulas + 15 practice questions.</p></div></div></section><section className="mx-auto max-w-4xl px-5 py-10 md:px-8">
 {stage==="intro"&&<div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><b className="block text-sm text-[#1B3A6B]">20 Questions</b><span className="text-xs text-slate-500">5 concepts + 15 practice</span></div><div className="rounded-2xl bg-red-50 p-4"><b className="block text-sm text-[#C8102E]">20 Marks</b><span className="text-xs text-slate-500">1 mark each</span></div><div className="rounded-2xl bg-emerald-50 p-4"><b className="block text-sm text-emerald-700">Instant Result</b><span className="text-xs text-slate-500">See your score immediately</span></div></div><h2 className="mt-8 text-2xl font-black">Before you start</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600"><li>• Review Class 1: Motion and Kinematics.</li><li>• Questions 1–5 test definitions and formulas from the class.</li><li>• Questions 6–20 are practice problems based on the same formulas and concepts.</li><li>• Enter your real name and phone number so your result can be saved.</li><li>• You can submit this assignment only once.</li></ul><div className="mt-8 grid gap-4 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" className="rounded-xl border border-slate-300 px-4 py-3.5 outline-none focus:border-[#1B3A6B]"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number" inputMode="tel" className="rounded-xl border border-slate-300 px-4 py-3.5 outline-none focus:border-[#1B3A6B]"/></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<button onClick={start} disabled={loading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#C8102E] px-5 py-4 font-black text-white hover:bg-[#a90d27] disabled:opacity-60">{loading?"Checking...":"Answer Now"}<ArrowRight className="h-5 w-5"/></button></div>}
 {stage==="quiz"&&<div className="space-y-5"><div className="sticky top-[76px] z-20 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-sm backdrop-blur"><div className="flex items-center justify-between gap-4"><b className="text-sm">Physics · Assignment 1</b><span className="text-xs font-black text-[#1B3A6B]">{answers.filter(a=>a>=0).length}/20 answered</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#C8102E]" style={{width:(answers.filter(a=>a>=0).length*5)+"%"}}/></div></div><div className="mb-2 rounded-2xl bg-[#EEF4FB] p-4 text-sm font-bold text-[#1B3A6B]">Part A · Definitions & Formulas — Questions 1–5</div>{QUESTIONS.map((item,i)=><div key={i}>{i===5&&<div className="mb-2 mt-7 rounded-2xl bg-[#FFF3E8] p-4 text-sm font-bold text-[#9A4B00]">Part B · Practice — Questions 6–20</div>}<div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#1B3A6B] text-xs font-black text-white">{i+1}</span><div className="flex-1"><h2 className="text-base font-black leading-7">{item.q}</h2><div className="mt-4 grid gap-2">{item.options.map((op,j)=><label key={j} className={"flex cursor-pointer items-start gap-3 rounded-xl border p-3 text-sm transition "+(answers[i]===j?"border-[#1B3A6B] bg-blue-50":"border-slate-200 hover:bg-slate-50")}><input type="radio" name={"q"+i} checked={answers[i]===j} onChange={()=>setAnswers(a=>{const n=[...a];n[i]=j;return n;})} className="mt-1 accent-[#1B3A6B]"/><span>{op}</span></label>)}</div></div></div></div>)}{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<button onClick={submit} disabled={loading} className="w-full rounded-2xl bg-[#C8102E] px-5 py-4 text-base font-black text-white shadow-lg hover:bg-[#a90d27] disabled:opacity-60">{loading?"Submitting...":"Finish Homework & See Result"}</button></div>}
 </section></main>;
}
