import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, ChevronDown, Download, ExternalLink, FileAudio, FileText, Headphones, Languages, MessageSquareText, PlayCircle, Sparkles, Target, Trophy, Users } from "lucide-react";

const official="https://www.chinesetest.cn/";
const officialHub="https://www.chinesetest.cn/Development";
const syllabus="https://hsk.cn-bj.ufileos.com/3.0/%E6%96%B0%E7%89%88HSK%E8%80%83%E8%AF%95%E5%A4%A7%E7%BA%B21219.pdf";
const competency="https://hsk.cn-bj.ufileos.com/3.0/HSK3.0%E8%80%83%E8%AF%95%E8%83%BD%E5%8A%9B%E6%8F%8F%E8%BF%B0.pdf";

const levels=[
[1,"150","Simple daily communication"],[2,"300","Basic daily, study and work communication"],[3,"600","Effective communication in common situations"],[4,"1,200","Complete and coherent communication"],[5,"2,500","Accurate communication in study and work"],[6,"5,000","Rich and fluent professional communication"],[7,"—","Advanced professional and academic communication"],[8,"—","Deep, appropriate and sophisticated communication"],[9,"—","Precise, deep professional and academic communication"]
];
const faqs=[
["Is this site based on HSK 3.0?","Yes. GL Education's learning and practice path is designed around HSK 3.0. Official CTI notices should always be checked for the latest examination arrangements."],
["How many HSK 3.0 levels are there?","HSK 3.0 uses nine proficiency levels. HSK 7–9 are assessed through the advanced HSK 7–9 examination and then classified into level 7, 8 or 9."],
["Where do I register for the real HSK exam?","Use the official Chinese Test Service Website and follow the test-center instructions for your location."],
["Are GL Education practice tests official papers?","No. GL Education practice tests are preparation tools. Official CTI resources are clearly labelled as official."],
["Can I study vocabulary by level and lesson?","The practice hub is designed for level-wise vocabulary, flashcards, MCQs and lesson-focused practice. The vocabulary data layer can be expanded from the official HSK 3.0 syllabus dataset."]
];

function Contact(){return <div className="flex justify-end"><div className="text-right"><div className="h-7 overflow-hidden text-sm font-black text-white"><div className="hsk-brand-rotate"><div className="h-7 leading-7">Study in China</div><div className="h-7 leading-7 text-[#FFD700]">GL Education</div></div></div><div className="mt-1 text-xs font-semibold text-slate-300">Contact GL Education</div><div className="h-5 overflow-hidden text-xs font-bold text-white"><div className="hsk-contact-rotate"><div className="h-5 leading-5"><a href="https://wa.me/8801901923239" target="_blank" rel="noreferrer">+8801901923239</a><span className="mx-1.5 text-slate-500">•</span><a href="https://wa.me/8615655031556" target="_blank" rel="noreferrer">+8615655031556</a></div><div className="h-5 leading-5 text-[#FFD700]"><a href="https://wa.me/8801901923239" target="_blank" rel="noreferrer">Click here to Chat</a></div></div></div></div></div>}

export default function HskPage(){
const jsonLd={"@context":"https://schema.org","@type":"WebPage","name":"HSK 3.0 Exam Guide, Materials & Free Practice Tests","description":"HSK 3.0 study hub with exam information, materials, vocabulary practice and mock tests.","url":"https://globlearnedu.com/hsk","isPartOf":{"@type":"WebSite","name":"GL Education","url":"https://globlearnedu.com"}};
return <main className="min-h-screen bg-slate-50 text-[#0A1628]">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
<section className="bg-[#0A1628] text-white"><div className="mx-auto max-w-7xl px-5 py-5 md:px-8"><Contact/><div className="grid gap-10 py-14 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-[#FFD700]"><Sparkles className="h-4 w-4"/> HSK 3.0 Study Hub</span><h1 className="mt-6 text-4xl font-black leading-tight md:text-6xl">HSK 3.0 Exam Guide, Materials & Free Practice Tests</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">A complete Chinese proficiency study hub covering HSK 1–9, official resources, vocabulary practice, mock tests and exam preparation.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={official} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#C8102E] px-6 py-3.5 font-black text-white">Register for HSK <ExternalLink className="h-4 w-4"/></a><Link href="/hsk/practice" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 font-black text-[#0A1628]">Free Practice Test <ArrowRight className="h-4 w-4"/></Link></div></div><div className="rounded-[2rem] border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-3"><Target className="h-6 w-6 text-[#29ABE2]"/><b>New-module focused</b></div><div className="mt-6 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/5 p-4 text-center"><b className="block text-3xl">9</b><span className="text-xs text-slate-400">Levels</span></div><div className="rounded-2xl bg-white/5 p-4 text-center"><b className="block text-3xl">4+</b><span className="text-xs text-slate-400">Skills</span></div><div className="rounded-2xl bg-white/5 p-4 text-center"><b className="block text-3xl">∞</b><span className="text-xs text-slate-400">Practice</span></div></div><p className="mt-5 text-sm leading-6 text-slate-400">CTI publishes the HSK 3.0 syllabus, sample questions, competency profile and official notices. Those sources are the reference point for real exam information.</p></div></div></div></section>

<section className="border-b bg-white"><div className="mx-auto max-w-7xl px-5 py-4 md:px-8"><div className="flex flex-wrap gap-2 text-sm font-bold"><a href="#levels" className="rounded-full bg-slate-100 px-4 py-2">Levels 1–9</a><a href="#materials" className="rounded-full bg-slate-100 px-4 py-2">HSK Materials</a><a href="#exam" className="rounded-full bg-slate-100 px-4 py-2">Exam Format</a><Link href="/hsk/practice" className="rounded-full bg-[#C8102E] px-4 py-2 text-white">Practice Hub</Link></div></div></section>

<section id="levels" className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="max-w-3xl"><span className="text-xs font-black uppercase tracking-[.18em] text-[#C8102E]">HSK 3.0 levels</span><h2 className="mt-2 text-3xl font-black md:text-4xl">Choose your target HSK level</h2><p className="mt-3 leading-7 text-slate-600">HSK 3.0 is organized across nine proficiency levels. HSK 7–9 are assessed through one advanced test and then classified into level 7, 8 or 9.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{levels.map(([n,w,d])=><a key={n} href={Number(n)<=6?"/hsk/practice?mode=mock&level="+n:"/hsk/practice?mode=mock&level=7-9"} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><div><span className="text-xs font-black uppercase text-slate-400">HSK</span><h3 className="text-3xl font-black">{n}</h3></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{w} words*</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{d}</p><div className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#1B3A6B]">Practice Level {n}<ArrowRight className="h-4 w-4"/></div></a>)}</div><p className="mt-4 text-xs text-slate-500">*Use the current HSK 3.0 syllabus as the authoritative vocabulary source; figures shown here are study references.</p></section>

<section id="exam" className="bg-[#0A1628] text-white"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8"><span className="text-xs font-black uppercase tracking-[.18em] text-[#FFD700]">New module first</span><h2 className="mt-2 text-3xl font-black md:text-4xl">Prepare for HSK 3.0, not the legacy path</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">The GL Education practice roadmap is built around HSK 3.0. Use official CTI pages for the exact test structure, registration dates and official announcements.</p><div className="mt-8 grid gap-4 md:grid-cols-4"><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><Headphones className="text-[#29ABE2]"/><h3 className="mt-4 font-black">Listening</h3><p className="mt-2 text-sm leading-6 text-slate-400">Timed listening, replay and section review.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><BookOpen className="text-[#29ABE2]"/><h3 className="mt-4 font-black">Reading</h3><p className="mt-2 text-sm leading-6 text-slate-400">Level-targeted reading speed and comprehension.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><Languages className="text-[#29ABE2]"/><h3 className="mt-4 font-black">Writing</h3><p className="mt-2 text-sm leading-6 text-slate-400">Sentence and extended-response practice.</p></div><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><MessageSquareText className="text-[#29ABE2]"/><h3 className="mt-4 font-black">Speaking</h3><p className="mt-2 text-sm leading-6 text-slate-400">Speaking and advanced HSK 7–9 preparation.</p></div></div><div className="mt-8 rounded-3xl border border-[#C8102E]/30 bg-[#C8102E]/10 p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><b className="text-lg">Official HSK 3.0 resources</b><p className="mt-1 text-sm text-slate-300">Syllabus, sample questions, competency profile and official notices.</p></div><a href={officialHub} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-black text-[#0A1628]">Open CTI resources <ExternalLink className="h-4 w-4"/></a></div></div></div></section>

<section id="materials" className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="max-w-3xl"><span className="text-xs font-black uppercase tracking-[.18em] text-[#C8102E]">Study library</span><h2 className="mt-2 text-3xl font-black md:text-4xl">HSK Materials</h2><p className="mt-3 leading-7 text-slate-600">Official-resource navigation plus a clear structure for books, workbooks, solutions, audio and sample questions. Legacy HSK 1–6 materials are reference only; the new practice path is HSK 3.0.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-3">
<div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><BookOpen className="text-[#C8102E]"/><h3 className="text-xl font-black">Official Books</h3></div><p className="mt-2 text-sm leading-6 text-slate-600">Reference the legacy Level 1–6 series and the new Level 1–9 framework.</p><div className="mt-5 space-y-2">{["Old HSK · Level 1","Old HSK · Level 2","Old HSK · Level 3","Old HSK · Level 4","Old HSK · Level 5","Old HSK · Level 6","New HSK 3.0 · Level 1–9"].map(x=><div key={x} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-sm"><span className="font-bold">{x}</span><a href={officialHub} target="_blank" rel="noreferrer" aria-label={"Official source for "+x}><ExternalLink className="h-4 w-4 text-[#1B3A6B]"/></a></div>)}</div><div className="mt-5 rounded-2xl bg-amber-50 p-4 text-xs leading-5 text-amber-800"><b>Audio:</b> book-audio download buttons should point only to audio you own or are authorized to redistribute. The current uploaded ZIP contains sample-test audio, not a complete licensed book-audio library.</div></div>
<div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><FileText className="text-[#C8102E]"/><h3 className="text-xl font-black">Official Workbooks</h3></div><p className="mt-2 text-sm leading-6 text-slate-600">Level-by-level workbook navigation with a dedicated place for official solution notes when available.</p><div className="mt-5 space-y-2">{[1,2,3,4,5,6].map(n=><div key={n} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3"><span className="text-sm font-bold">Workbook · HSK {n}</span><a href={officialHub} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-black text-[#1B3A6B]">Official source <ExternalLink className="h-3 w-3"/></a></div>)}</div><p className="mt-4 text-xs text-slate-500">Licensed solution PDFs can be attached to each level without changing the interface.</p></div>
<div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Trophy className="text-[#C8102E]"/><h3 className="text-xl font-black">Official Sample Questions</h3></div><p className="mt-2 text-sm leading-6 text-slate-600">Go directly to CTI's official HSK 3.0 sample resources and download the current syllabus documents.</p><div className="mt-5 space-y-3"><a href={officialHub} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold">CTI sample-question hub <ExternalLink className="h-4 w-4"/></a><a href={syllabus} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold">HSK 3.0 syllabus PDF <Download className="h-4 w-4"/></a><a href={competency} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold">Competency profile PDF <Download className="h-4 w-4"/></a></div></div>
</div><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><b className="text-lg">Official HSK 3.0 syllabus</b><p className="mt-1 text-sm text-slate-600">The current published syllabus is the source of truth for tasks, vocabulary, characters and grammar.</p></div><a href={syllabus} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#1B3A6B] px-5 py-3 font-black text-white">Download syllabus <Download className="h-4 w-4"/></a></div></div></section>

<section className="border-y bg-white"><div className="mx-auto max-w-7xl px-5 py-14 md:px-8"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-slate-50 p-6"><FileAudio className="text-[#C8102E]"/><h3 className="mt-4 font-black">Audio practice</h3><p className="mt-2 text-sm leading-6 text-slate-600">Organize listening files by level, section and test set with replay and progress controls.</p></div><div className="rounded-3xl bg-slate-50 p-6"><PlayCircle className="text-[#C8102E]"/><h3 className="mt-4 font-black">Real-test mode</h3><p className="mt-2 text-sm leading-6 text-slate-600">Timed mock tests keep answers hidden until submission and save progress automatically.</p></div><div className="rounded-3xl bg-slate-50 p-6"><Users className="text-[#C8102E]"/><h3 className="mt-4 font-black">GL Education support</h3><p className="mt-2 text-sm leading-6 text-slate-600">A dedicated pathway for students preparing Chinese for study in China.</p></div></div></div></section>

<section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="max-w-3xl"><span className="text-xs font-black uppercase tracking-[.18em] text-[#C8102E]">FAQ</span><h2 className="mt-2 text-3xl font-black">HSK 3.0 questions students ask</h2></div><div className="mt-7 space-y-3">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-black">{q}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="mt-4 max-w-4xl text-sm leading-7 text-slate-600">{a}</p></details>)}</div></section>
<section className="bg-[#0A1628] text-white"><div className="mx-auto max-w-7xl px-5 py-14 text-center md:px-8"><CheckCircle2 className="mx-auto h-9 w-9 text-[#29ABE2]"/><h2 className="mt-4 text-3xl font-black">Start your HSK 3.0 preparation</h2><p className="mx-auto mt-3 max-w-2xl text-slate-300">Choose a level, practice vocabulary, take a mock test and track your progress.</p><Link href="/hsk/practice" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#C8102E] px-6 py-3.5 font-black text-white">Open Free Practice Hub <ArrowRight className="h-4 w-4"/></Link></div></section>
</main>;
}
