import {
  emailVerificationTemplate,
  passwordResetTemplate,
  applicationReceivedStudent,
  applicationReceivedPartner,
  statusUpdateEmail,
  admissionOfferEmail,
  documentActionRequiredEmail,
  paymentConfirmationEmail,
  admissionCompleteEmail,
  partnerApprovedEmail,
  referralCommissionEmail,
  interviewScheduledEmail,
  visaGuidancePackEmail,
} from "./templates";

// Each template is seeded by calling the hardcoded function with {{variableName}} placeholders.
// Admin can then edit subject/bodyHtml in the UI; {{variableName}} gets substituted at send time.

export const SEED_TEMPLATES = [
  {
    name: "Email Verification",
    triggerEvent: "email_verification",
    category: "Auth",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    ...emailVerificationTemplate({ firstName: "{{firstName}}", verifyUrl: "{{verifyUrl}}" }),
    bodyHtml: emailVerificationTemplate({ firstName: "{{firstName}}", verifyUrl: "{{verifyUrl}}" }).html,
  },
  {
    name: "Password Reset",
    triggerEvent: "password_reset",
    category: "Auth",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    ...passwordResetTemplate({ firstName: "{{firstName}}", resetUrl: "{{resetUrl}}" }),
    bodyHtml: passwordResetTemplate({ firstName: "{{firstName}}", resetUrl: "{{resetUrl}}" }).html,
  },
  {
    name: "Application Received (Student)",
    triggerEvent: "application_received_student",
    category: "Application",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: applicationReceivedStudent({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universities: ["{{universities}}"], program: "{{program}}", trackingUrl: "{{trackingUrl}}" }).subject,
    bodyHtml: applicationReceivedStudent({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universities: ["{{universities}}"], program: "{{program}}", trackingUrl: "{{trackingUrl}}" }).html,
  },
  {
    name: "Application Received (Partner)",
    triggerEvent: "application_received_partner",
    category: "Application",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: false,
    sendToPartner: true,
    subject: applicationReceivedPartner({ partnerName: "{{partnerName}}", studentName: "{{studentName}}", applicationId: "{{applicationId}}", program: "{{program}}" }).subject,
    bodyHtml: applicationReceivedPartner({ partnerName: "{{partnerName}}", studentName: "{{studentName}}", applicationId: "{{applicationId}}", program: "{{program}}" }).html,
  },
  {
    name: "Application Status Update",
    triggerEvent: "status_update",
    category: "Application",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: statusUpdateEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", newStatus: "{{newStatus}}", statusDescription: "{{statusDescription}}", nextStep: "{{nextStep}}", trackingUrl: "{{trackingUrl}}" }).subject,
    bodyHtml: statusUpdateEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", newStatus: "{{newStatus}}", statusDescription: "{{statusDescription}}", nextStep: "{{nextStep}}", trackingUrl: "{{trackingUrl}}" }).html,
  },
  {
    name: "Admission Offer",
    triggerEvent: "admission_offer",
    category: "Admission",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: admissionOfferEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", programName: "{{programName}}", scholarshipType: "{{scholarshipType}}", intakeDate: "{{intakeDate}}", staffName: "{{staffName}}", trackingUrl: "{{trackingUrl}}" }).subject,
    bodyHtml: admissionOfferEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", programName: "{{programName}}", scholarshipType: "{{scholarshipType}}", intakeDate: "{{intakeDate}}", staffName: "{{staffName}}", trackingUrl: "{{trackingUrl}}" }).html,
  },
  {
    name: "Document / Action Required",
    triggerEvent: "document_action_required",
    category: "Application",
    isAutoTrigger: false,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: documentActionRequiredEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", section: "{{section}}", instructions: "{{instructions}}" }).subject,
    bodyHtml: documentActionRequiredEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", section: "{{section}}", instructions: "{{instructions}}" }).html,
  },
  {
    name: "Payment Confirmed",
    triggerEvent: "payment_confirmed",
    category: "Payment",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: paymentConfirmationEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", amount: "{{amount}}", currency: "{{currency}}", paymentType: "{{paymentType}}" }).subject,
    bodyHtml: paymentConfirmationEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", amount: "{{amount}}", currency: "{{currency}}", paymentType: "{{paymentType}}" }).html,
  },
  {
    name: "Admission Complete",
    triggerEvent: "admission_complete",
    category: "Admission",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: admissionCompleteEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", programName: "{{programName}}", guideUrl: "{{guideUrl}}" }).subject,
    bodyHtml: admissionCompleteEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", programName: "{{programName}}", guideUrl: "{{guideUrl}}" }).html,
  },
  {
    name: "Partner Account Approved",
    triggerEvent: "partner_approved",
    category: "Partner",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: false,
    sendToPartner: true,
    subject: partnerApprovedEmail({ partnerName: "{{partnerName}}", agencyName: "{{agencyName}}" }).subject,
    bodyHtml: partnerApprovedEmail({ partnerName: "{{partnerName}}", agencyName: "{{agencyName}}" }).html,
  },
  {
    name: "Referral Commission Earned",
    triggerEvent: "referral_commission",
    category: "Partner",
    isAutoTrigger: true,
    isActive: true,
    sendToStudent: false,
    sendToPartner: true,
    subject: referralCommissionEmail({ referrerName: "{{referrerName}}", referredStudentFirstName: "{{referredStudentFirstName}}", commissionAmount: "{{commissionAmount}}", totalEarned: "{{totalEarned}}" }).subject,
    bodyHtml: referralCommissionEmail({ referrerName: "{{referrerName}}", referredStudentFirstName: "{{referredStudentFirstName}}", commissionAmount: "{{commissionAmount}}", totalEarned: "{{totalEarned}}" }).html,
  },
  {
    name: "Interview Scheduled",
    triggerEvent: "interview_scheduled",
    category: "Application",
    isAutoTrigger: false,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: interviewScheduledEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", interviewDate: "{{interviewDate}}", interviewTime: "{{interviewTime}}", timezone: "{{timezone}}", platform: "{{platform}}", link: "{{link}}", duration: "{{duration}}", language: "{{language}}", guidelines: "{{guidelines}}" }).subject,
    bodyHtml: interviewScheduledEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", interviewDate: "{{interviewDate}}", interviewTime: "{{interviewTime}}", timezone: "{{timezone}}", platform: "{{platform}}", link: "{{link}}", duration: "{{duration}}", language: "{{language}}", guidelines: "{{guidelines}}" }).html,
  },
  {
    name: "Visa Guidance Pack",
    triggerEvent: "visa_guidance_pack",
    category: "Visa",
    isAutoTrigger: false,
    isActive: true,
    sendToStudent: true,
    sendToPartner: false,
    subject: visaGuidancePackEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", visaGuideUrl: "{{visaGuideUrl}}" }).subject,
    bodyHtml: visaGuidancePackEmail({ studentName: "{{studentName}}", applicationId: "{{applicationId}}", universityName: "{{universityName}}", visaGuideUrl: "{{visaGuideUrl}}" }).html,
  },
] as const;

// Template variable reference shown in the editor
export const TEMPLATE_VARIABLES: Record<string, string[]> = {
  email_verification:             ["firstName", "verifyUrl"],
  password_reset:                 ["firstName", "resetUrl"],
  application_received_student:  ["studentName", "applicationId", "program", "universities", "trackingUrl"],
  application_received_partner:  ["partnerName", "studentName", "applicationId", "program"],
  status_update:                  ["studentName", "applicationId", "newStatus", "statusDescription", "nextStep", "trackingUrl"],
  admission_offer:                ["studentName", "applicationId", "universityName", "programName", "scholarshipType", "intakeDate", "staffName", "trackingUrl"],
  document_action_required:       ["studentName", "applicationId", "section", "instructions"],
  payment_confirmed:              ["studentName", "applicationId", "amount", "currency", "paymentType"],
  admission_complete:             ["studentName", "applicationId", "universityName", "programName", "guideUrl"],
  partner_approved:               ["partnerName", "agencyName"],
  referral_commission:            ["referrerName", "referredStudentFirstName", "commissionAmount", "totalEarned"],
  interview_scheduled:            ["studentName", "applicationId", "universityName", "interviewDate", "interviewTime", "timezone", "platform", "duration", "language", "guidelines", "link"],
  visa_guidance_pack:             ["studentName", "applicationId", "universityName", "visaGuideUrl"],
};
